---

- name: create Tuleap docker structure on server in /home/docker/tuleap
  file:
    name: /home/docker/tuleap
    state: directory
    owner: root
    group: root

- name: copy mysql configuration file
  copy:
    src: sql_mode.cnf
    dest: /home/docker/tuleap/sql_mode.cnf
    owner: root
    group: root
    mode: 0644

- name: Install tuleap docker
  template:
    src: tuleap.yaml.j2
    dest: /home/docker/tuleap/docker-compose.yaml
    owner: root
    group: root
    mode: 0400
  notify: 
    - start tuleap docker

## Backup tuleap section
- name: Install tuleap backup compose file
  template:
    src: backup.yaml.j2
    dest: /home/docker/backups/backup-tuleap.yaml
    owner: root
    group: root
    mode: 0400
  when: inventory_hostname in groups['maintenance_contract']

- name: Copy docker file for mysql duplicity
  copy:
    src: ../docker_nextcloud/files/Dockerfile-backup
    dest: /home/docker/backups/Dockerfile-mysql
    owner: root
    group: root
    mode: 0644
  when: inventory_hostname in groups['maintenance_contract']

- name: add cron job to run backup every week
  cron:
    name: backup tuleap
    minute: 03
    hour: 4
    job: /usr/local/bin/docker-compose -f /home/docker/backups/backup-tuleap.yaml run --rm backup_tuleap 
  when: inventory_hostname in groups['maintenance_contract']
